{% set version = "0.9.1" %}

package:
  name: cargo-llvm-cov
  version: {{ version }}

source:
  url: https://github.com/taiki-e/cargo-llvm-cov/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7cfe2b19ea8c86f997750ac227d3b166b79e5e23a58074bd59134cfb5d0fb22c

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  requires:
    - {{ compiler('rust') }}
  commands:
    - cargo llvm-cov --help

about:
  home: https://github.com/taiki-e/cargo-llvm-cov
  license: Apache-2.0
  license_family: Apache
  summary: Cargo subcommand to easily use LLVM source-based code coverage (-C instrument-coverage).
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - borchero
