{% set version = "0.6.17" %}

package:
  name: cargo-llvm-cov
  version: {{ version }}

source:
  url: https://github.com/taiki-e/cargo-llvm-cov/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fbc827c62136abbdced662b6b6cca2489f6e4c1ca2a175f8c76e6a0babbbdc4a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  requires:
    - {{ compiler('rust') }}
  commands:
    - cargo llvm-cov --help

about:
  home: https://github.com/taiki-e/cargo-llvm-cov
  license: Apache-2.0
  license_family: Apache
  summary: Cargo subcommand to easily use LLVM source-based code coverage (-C instrument-coverage).
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - borchero
