{% set version = "0.6.12" %}

package:
  name: cargo-llvm-cov
  version: {{ version }}

source:
  url: https://github.com/taiki-e/cargo-llvm-cov/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 165185c74e59ca26878c989366efe03d2a28409c0bdfb2dcce7ab34580395588

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  requires:
    - {{ compiler('rust') }}
  commands:
    - cargo llvm-cov --help  # [build_platform == target_platform]

about:
  home: https://github.com/taiki-e/cargo-llvm-cov
  license: Apache-2.0
  license_family: Apache
  summary: Cargo subcommand to easily use LLVM source-based code coverage (-C instrument-coverage).
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - borchero
