{% set version = "0.8.6" %}

package:
  name: cargo-llvm-cov
  version: {{ version }}

source:
  url: https://github.com/taiki-e/cargo-llvm-cov/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 869de622c946f325724e1261600b4b775ac63394299897a464cde9910c18f22a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  requires:
    - {{ compiler('rust') }}
  commands:
    - cargo llvm-cov --help

about:
  home: https://github.com/taiki-e/cargo-llvm-cov
  license: Apache-2.0
  license_family: Apache
  summary: Cargo subcommand to easily use LLVM source-based code coverage (-C instrument-coverage).
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - borchero
